// Session
export const SESSION_LOAD = 'SESSION_LOAD';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const LOAD_USERBOARDS_FOR_PROFILE = 'LOAD_USERBOARDS_FOR_PROFILE';
export const LOAD_PINS = "LOAD_PINS";
export const LOAD_USERBOARDS_FOR_DISCOVER = 'LOAD_USERBOARDS_FOR_DISCOVER';
export const SHOW_PIN = "SHOW_PIN";
export const LOAD_EXISTING_BOARD = "LOAD_EXISTING_BOARD";

export const LOAD_BOARD = "LOAD_BOARD";
export const CLEAN_BOARD = "CLEAN_BOARD";
export const LOAD_STATES = "LOAD_STATES";

export const LOAD_PUBLIC_BOARDS = "LOAD_PUBLIC_BOARDS";
export const LOAD_INVITED_BOARDS = "LOAD_INVITED_BOARDS";
export const LOAD_PRIVATE_BOARDS = "LOAD_PRIVATE_BOARDS";
export const LOAD_IS_CURRENT_USER = "LOAD_IS_CURRENT_USER";

export const LOAD_USER_SEARCH_RESULT = "LOAD_SEARCH_RESULT";
export const LOAD_BOARD_SEARCH_RESULT = "LOAD_BOARD_SEARCH_RESULT";
export const LOAD_PIN_SEARCH_RESULT = "LOAD_SEARCH_RESULT";
export const LOAD_ACTIVE_BOARD = "LOAD_ACTIVE_BOARD";
export const LOAD_ACTIVE_PIN = "LOAD_ACTIVE_PIN";

export const LOAD_MY_FEEDS = "LOAD_MY_FEEDS";
export const LOAD_INVITES = "LOAD_INVITES";
export const UPLOAD_RIFF = "UPLOAD_RIFF";
export const LOAD_POPULAR = "LOAD_POPULAR";