// Session
export const SESSION_LOAD = 'SESSION_LOAD';
export const SESSION_LOGIN = 'SESSION_LOGIN';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';

export const PROFILE_LOAD = 'PROFILE_LOAD';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const LOAD_USERBOARDS_FOR_PROFILE = 'LOAD_USERBOARDS_FOR_PROFILE';

export const LOAD_PINS = "LOAD_PINS";

export const LOAD_USERBOARDS_FOR_DISCOVER = 'LOAD_USERBOARDS_FOR_DISCOVER';
